disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_comma
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Places
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

large_tuple:
  - 3 # Warning
  - 3 # Error

type_body_length:
  - 400 # Warning
  - 550 # Error
cyclomatic_complexity: 
  ignores_case_statements: true

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 
    warning: 90
    error: 1000

type_name:
  min_length: 1
  max_length:
    warning: 50
    error: 60
warning_threshold: 1

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)